#!/bin/sh -e
echo "DEBUG: EXECUTING PREINST SCRIPT"
FROM_VERSION=$(dpkg-query --show --showformat='${Version}' ces-commons)
echo "DEBUG: UPGRADING FROM VERSION ${FROM_VERSION}"
prepare_upgrade_from_v0_1_4_or_earlier() {
  if [ ! -f "/var/lib/dpkg/info/ces-commons.conffiles" ] && [ -f /etc/ces/functions.sh ]; then
      rm /etc/ces/functions.sh
  fi
}

prepare_upgrade_from_v0_2_1_or_earlier() {
  dockerServiceDir="/etc/systemd/system/docker.service.d"
  dockerOptionsConfFile="${dockerServiceDir}/dockeroptions.conf"

  if [ -f "${dockerOptionsConfFile}" ]; then
    # Add ".old" to current options file
    oldDockerOptionsConfFile="${dockerOptionsConfFile}.old"
    mv "${dockerOptionsConfFile}" "${oldDockerOptionsConfFile}"
    # Comment out all lines in old options file
    sed -i -e 's/^/#/' "${oldDockerOptionsConfFile}"
  fi
}

if dpkg --compare-versions "${FROM_VERSION}" "le" "0.1.4"; then
  echo "DEBUG: UPGRADING FROM A VERSION LOWER OR EQUAL TO 0.1.4"
  prepare_upgrade_from_v0_1_4_or_earlier
fi

if dpkg --compare-versions "${FROM_VERSION}" "le" "0.2.1"; then
  echo "DEBUG: UPGRADING FROM A VERSION LOWER OR EQUAL TO 0.2.1"
  prepare_upgrade_from_v0_2_1_or_earlier
fi